---
- name: changing the hostname
  become: yes
  hosts: switches
  tasks:

      - name: Apply the provided configuration
        cisco.ios.ios_hostname:
          config:
          hostname: Router1
          state: replaced
