---
# Lets install apache in Debain and Centos
- name: "install apache2 in both servers"
  hosts: machines
  become: true
  gather_facts: true
  tasks:
    - name: Installing apache2 in debian 
      when: ansible_distribution == "Debian"
      apt:
        name: apache2
        state: latest
    - name: enabling the apache2
      service:
        name: apache2
        state: started
    - name: Install apache in Centos
      when: ansible_distribution == "CentOS"
      yum:
         name: httpd
         state: latest
    - name: enabling the apache service for booting when restarting the systems
      service:
        name: httpd
        state: started
